In [1]:
# without using numpy
temperature=[32.5,36.7,35.7,32.3,38.6]

total=0
for temp in temperature:
    total+=temp

average=total/len(temperature)
print(average)

35.16


In [4]:
# using numpy
import numpy as np

temperature=np.array([32.5,36.7,35.7,32.3,38.6])
average=np.mean(temperature)
print(average)


35.16


In [1]:
# creating numpy array (1 D array)

import numpy as np
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [2]:
# (2-D array)
import numpy as np
array=np.array([[1,2,3],
               [5,6,7],
               [5,6,7]])
print(array)

[[1 2 3]
 [5 6 7]
 [5 6 7]]


In [3]:
# (Multi-D array)
import numpy as np
matrix=np.array([[1,2,3],
                 [5,6,7],])
print(matrix)

[[1 2 3]
 [5 6 7]]


In [4]:
# creating array from python list
import numpy as np
array=np.array([1,2,3,4,5])
print(array)


[1 2 3 4 5]


In [6]:
# Special Numpy Arrays (zero()-array of zeros)
import numpy as np
array=np.zeros((3,3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# ones() -  arrays of ones
import numpy as np
t=np.ones((2,3))
print(t)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# full() - arrays with a constant value
import numpy as np
t=np.full((3,3),7)
print(t)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
# empty()
import numpy as np
e=np.empty((3,3))
print(e)

[[4.67296746e-307 1.69121096e-306 1.33511018e-306]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 5.53353523e-322]]


In [11]:
# arange() - Range of Values
import numpy as np
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [13]:
# eye() - identify matrix
import numpy as np
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# numpy arrays properties
import numpy as np
array=np.array([[1,2,3],
               [4,5,6],
                [7,8,9]])
array2=np.array([
    [[1,2,3],[4,5,6]],
    [[4,3,2],[6,7,8]]
    ])
print(array.shape) # Dimensions of Array
print(array.size) # Total number of elements
print(array.ndim) # Number of dimensions
print(array2.shape)
print(array2.ndim)
print(array2.size)
print(array.dtype) # Data type of element
print(array2.dtype)

(3, 3)
9
2
(2, 2, 3)
3
12
int64
int64


In [12]:
# Numpy astype() Method
import numpy as np
array=np.array([1.2,3.3,4.9,5.2])
new_array=array.astype(int)
print(array.dtype)
print(new_array)
print(new_array.dtype)

float64
[1 3 4 5]
int64


In [13]:
# Mathematical Operation in numpy
import numpy as np
arr=np.array([10,20,30])
print(arr+2)
print(arr-2)
print(arr*2)
print(arr**2)
print(arr/2)

[12 22 32]
[ 8 18 28]
[20 40 60]
[100 400 900]
[ 5. 10. 15.]


In [17]:
# Aggregate Function
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


36
1
8
4.5
4.5
2.29128784747792
5.25


In [3]:
# indexing
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2])
print(arr[0])
print(arr[-1])

3
1
5


In [7]:
# slicing
import numpy as np
arr=np.array([10,20,30,40])
print(arr[1:5])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[20 30 40]
[10 20 30 40]
[10 30]
[40 30 20 10]


In [9]:
# fancy indexing
import numpy as np
arr=np.array([10,20,30,50])
print(arr[[1,2,3]])

[20 30 50]


In [10]:
# Boolean Indexing

import  numpy as np
arr=np.array([10,20,30,40])
print(arr[arr>20])

[30 40]


In [13]:
# Reshaping array
import numpy as np
array=np.array([10,20,30,40,50,60])
print(array.reshape(3,2))
print(array.ndim)

[[10 20]
 [30 40]
 [50 60]]
1


In [14]:
# Flatten and Ravel
array=np.array([[1,2,3],[4,5,6]])
print(array.flatten())
print(array.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [15]:
# Array Modification (Advance NumPy)
import numpy as np
array=([10,20,30,40,50,60])
print(array)
new_array=np.insert(array,2,100)
print(new_array)

[10, 20, 30, 40, 50, 60]
[ 10  20 100  30  40  50  60]


In [23]:
# In Case of 2D array
array2d=np.array([[1,2,3],[4,5,6]])
print(array2d)
new_arr=np.insert(array2d,0,[10,11,12],axis=0)
print(new_arr)
new_arr1=np.insert(array2d,0,[100,200],axis=1)
print(new_arr1)

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [ 1  2  3]
 [ 4  5  6]]
[[100   1   2   3]
 [200   4   5   6]]


In [24]:
# Append Element
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
arr2=np.append(arr,[9,8])
print(arr2)

[1 2 3 4]
[1 2 3 4 9 8]


In [33]:
# Concatenate
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
new=np.concatenate((arr1,arr2))
print(new)


[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
# Concatenate 2 D array
arr1=np.array([[1,2,3],
             [4,5,6]])
arr2=np.array([[6,7,8],
               [9,10,10]])
new=np.concatenate((arr1,arr2),axis=0)
print(new)
new=np.concatenate((arr1,arr2),axis=1)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 10]]
[[ 1  2  3  6  7  8]
 [ 4  5  6  9 10 10]]


In [2]:
# Removing element
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.delete(arr,2)
print(new_arr)
new=arr[arr>=30]
print(new)

[10 20 30 40 50 60]
[10 20 40 50 60]
[30 40 50 60]


In [7]:
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
new=np.delete(arr,0,axis=0)
print(new)


[[40 50 60]
 [70 80 90]]


In [10]:
# Stacking Array
import numpy as np
arr=np.array([10,20,30])
arr1=np.array([40,50,60])
new=np.vstack((arr,arr1))
print(new)
new=np.hstack((arr,arr1))
print(new)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [13]:
# Splitting Arrays
arr=np.array([10,20,30,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [16]:
# Broadcasting ( without using numpy)
prices=[100,200,300]
discount=10
new_price=[]
for price in prices:
    final_price=price-(price*discount/100)
    new_price.append(final_price)
print(new_price)


[90.0, 180.0, 270.0]


In [22]:
# using numpy
import numpy as np
prices= np.array([100,200,300])
discount=10
final_price=prices-(prices*discount/100)
print(final_price)

[ 90. 180. 270.]


In [23]:
# Broadcasting Single Value
arr=np.array([100,200,300])
result=arr*2
print(result)

[200 400 600]


In [24]:
# Broadcasting 1D to 2D array
matrix=np.array([[1,2,3],
                 [4,5,6]])
vector=np.array([10,20,30])
result=matrix+vector
print(result)

[[11 22 33]
 [14 25 36]]


In [25]:
# Broadcasting Error
arr=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([2,3])
result=arr+arr2
print(result)

# to solve this problem we can reshape te array with reshape function

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [26]:
# Vectorization
import numpy as np
arr=np.array([1,2,3,4,5])
result=arr*2
print(result)


[ 2  4  6  8 10]


In [27]:
# Handling missing value
import numpy as np
arr=np.array([1,2,np.nan,3,np.nan,6])
print(np.isnan(arr))

[False False  True False  True False]


In [29]:
# replacing NaN
import numpy as np
arr=np.array([1,2,np.nan,3,np.nan,6])
clean_arr=np.nan_to_num(arr,nan=100)
print(clean_arr)


[  1.   2. 100.   3. 100.   6.]


In [30]:
# infinity number
import numpy as np
arr=np.array([1,2,np.inf,3,-np.inf,6])
print(np.isinf(arr))

[False False  True False  True False]


In [2]:
x = int(input("Enter X: "))
y = int(input("Enter Y: "))

array = []

for i in range(x):
    row = []
    for j in range(y):
        row.append(i * j)
    array.append(row)

print(array)


[[0, 0, 0], [0, 1, 2], [0, 2, 4], [0, 3, 6], [0, 4, 8]]
